apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr-deployment
  labels: # used to organize and select subsets of Kubernetes objects.
    app: solrApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solrApp 
  template:
    metadata:
      labels:
        app: solrApp
    spec:
      containers:
      - name: solr
        image: solr
        ports:
        - containerPort: 8983
          name: solrapp
