apiVersion: v1
kind: Service
metadata:
  labels:
     app: solrApp
  name: solr-service
spec:
  selector:
    app: solrApp # set of Pods targeted by a Service. This matches pods with label solrApp
  ports:
  - port: 8983 #port exposed by the service
    targetPort: 8983 #target 8983 on any pod